# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  images: |
      image: docker.io/bitnami/kubectl:1.33.4-debian-12-r0
      image: docker.io/bitnami/os-shell:12-debian-12-r51
      image: docker.io/bitnami/redis-exporter:1.76.0-debian-12-r0
      image: docker.io/bitnami/valkey:8.1.3-debian-12-r3
      image: docker.io/bitnami/valkey-sentinel:8.1.3-debian-12-r3
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.1.3
dependencies:
- name: common
  repository: https://portswigger-cloud.github.io/legacy-charts/
  tags:
  - bitnami-common
  version: 2.x.x
description: Valkey is an open source (BSD) high-performance key/value datastore that
  supports a variety workloads such as caching, message queues, and can act as a primary
  database.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
keywords:
- valkey
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: valkey
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/valkey
version: 8.1.4