# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
      image: docker.io/bitnami/concourse:7.13.2-debian-12-r12
      image: docker.io/bitnami/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 7.13.2
description: Concourse is an automation system written in Go. It is most commonly
  used for CI/CD, and is built to scale to any kind of automation pipeline, from simple
  to complex.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/concourse/img/concourse-stack-220x234.png
keywords:
- concourse
- ci
- cd
- http
- web
- application
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: concourse
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/concourse
version: 1.0.0