# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: DeveloperTools
  images: |
      image: docker.io/bitnami/chainloop-artifact-cas:1.43.0-debian-12-r0
      image: docker.io/bitnami/chainloop-control-plane:1.43.0-debian-12-r0
      image: docker.io/bitnami/chainloop-control-plane-migrations:1.43.0-debian-12-r0
      image: docker.io/bitnami/dex:2.43.1-debian-12-r8
  license: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.43.0
dependencies:
- name: common
  repository: https://portswigger-cloud.github.io/legacy-charts/
  tags:
  - bitnami-common
  version: 2.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 17.x.x
- condition: development
  name: vault
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 1.x.x
description: Chainloop is an open-source Software Supply Chain control plane, a single
  source of truth for metadata and artifacts, plus a declarative attestation process.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/chainloop/img/chainloop-stack-220x234.png
keywords:
- chainloop
- evidence-store
- supply-chain-security
- devops
- devsecops
- security
- compliance
- cyclonedx
- spdx
- sbom
- attestation
- oss-compliance
- in-toto
- slsa
- sbom-distribution
- open-source-licensing
- slsa-provenance
- metadata-platform
- sbom-discovery
- regulated-industry
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: chainloop
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/chainloop
version: 1.43.0