# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
      image: docker.io/bitnami/kong:3.9.1-debian-12-r7
      image: docker.io/bitnami/kong-ingress-controller:3.5.1-debian-12-r3
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 3.9.1
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 17.x.x
- name: common
  repository: https://portswigger-cloud.github.io/legacy-charts/
  tags:
  - bitnami-common
  version: 2.x.x
- condition: cassandra.enabled
  name: cassandra
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 5.x.x
description: Kong is an open source Microservice API gateway and platform designed
  for managing microservices requests of high-availability, fault-tolerance, and distributed
  systems.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kong/img/kong-stack-220x234.png
keywords:
- kong
- ingress
- openresty
- controller
- http
- web
- www
- reverse proxy
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kong
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kong
version: 15.4.21-legacy