# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  images: |
      image: docker.io/bitnami/alertmanager:0.28.1-debian-12-r15
      image: docker.io/bitnami/blackbox-exporter:0.27.0-debian-12-r4
      image: docker.io/bitnami/prometheus:3.5.0-debian-12-r3
      image: docker.io/bitnami/prometheus-operator:0.85.0-debian-12-r0
      image: docker.io/bitnami/thanos:0.39.2-debian-12-r2
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.85.0
description: Prometheus Operator provides easy monitoring definitions for Kubernetes
  services and deployment and management of Prometheus instances.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/prometheus-operator/img/prometheus-operator-stack-220x234.png
keywords:
- prometheus
- alertmanager
- operator
- monitoring
kubeVersion: '>= 1.16.0-0'
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kube-prometheus
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kube-prometheus
version: 1.0.0# Updated for internal supply chain control
# Trigger release for chart repository publishing
