# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
      image: docker.io/bitnami/apache-exporter:1.0.10-debian-12-r55
      image: docker.io/bitnami/phpmyadmin:5.2.2-debian-12-r22
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 5.2.2
description: phpMyAdmin is a free software tool written in PHP, intended to handle
  the administration of MySQL over the Web. phpMyAdmin supports a wide range of operations
  on MySQL and MariaDB.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/phpmyadmin/img/phpmyadmin-stack-220x234.png
keywords:
- mariadb
- mysql
- phpmyadmin
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: phpmyadmin
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/phpmyadmin
version: 1.0.0