# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Infrastructure
  images: |
    - name: envoy
      image: docker.io/bitnami/envoy:1.35.1-debian-12-r0
    - name: envoy-gateway
      image: docker.io/bitnami/envoy-gateway:1.5.0-debian-12-r1
    - name: envoy-ratelimit
      image: docker.io/bitnami/envoy-ratelimit:2025.8.15-debian-12-r0
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 1.5.0
description: Envoy Gateway simplifies traffic management by extending Envoy Proxy's
  features, offering Kubernetes Gateway API integration for secure, scalable, and
  observable application routing
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/envoy-gateway/img/envoy-gateway-stack-220x234.png
keywords:
- envoy-gateway
- traffic
- gateway
- ingress
maintainers:
name: envoy-gateway
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/envoy-gateway
version: 2.0.4
