# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: CMS
  images: |
      image: docker.io/bitnami/mastodon:4.4.3-debian-12-r8
      image: docker.io/bitnami/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 4.4.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 16.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 22.x.x
- condition: minio.enabled
  name: minio
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 17.x.x
- condition: apache.enabled
  name: apache
  repository: https://portswigger-cloud.github.io/legacy-charts/
  version: 11.x.x
- name: common
  repository: https://portswigger-cloud.github.io/legacy-charts/
  tags:
  - bitnami-common
  version: 2.x.x
description: Mastodon is self-hosted social network server based on ActivityPub. Written
  in Ruby, features real-time updates, multimedia attachments and no vendor lock-in.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mastodon/img/mastodon-stack-220x234.png
keywords:
- development
- dashboards
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mastodon
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mastodon
version: 14.0.2