# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Analytics
  images: |
      image: docker.io/bitnami/kube-state-metrics:2.16.0-debian-12-r5
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 2.16.0
description: kube-state-metrics is a simple service that listens to the Kubernetes
  API server and generates metrics about the state of the objects.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kube-state-metrics/img/kube-state-metrics-stack-220x234.png
keywords:
- prometheus
- kube-state-metrics
- monitoring
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: kube-state-metrics
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/kube-state-metrics
version: 1.0.0# Updated for internal supply chain control
# Trigger release for chart repository publishing
